// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SDA Project - Class Diagram;



/************************************************************/
/**
 * 
 */
public class Admin extends User
 {
				/**
				 * 
				 */
				protected String Email;
				/**
				 * 
				 */
				protected String password;
	/**
	 * 
	 */
	public void ViewDonations() {
	}
	/**
	 * 
	 */
	public void ReviewRequests() {
	}
	/**
	 * 
	 * @param Request 
	 */
	public void ApproveRequest(Request Request) {
	}
	/**
	 * 
	 * @param Request 
	 */
	public void DenyRequest(Request Request) {
	}
	/**
	 * 
	 * @param Email 
	 * @param password 
	 */
	public void Login(String Email, String password) {
	}
}
