// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SDA Project - Class Diagram;



/************************************************************/
/**
 * 
 */
public class Donation {
				/**
				 * 
				 */
				public int donorID;
				/**
				 * 
				 */
				public int pointsEarned;
				/**
				 * 
				 */
				public int amountDonated;
				/**
				 * 
				 */
				protected int donationID;
				/**
				 * 
				 */
				protected EFloat amount;
				/**
				 * 
				 */
				protected String cause;
				/**
				 * 
				 */
				protected String type;
				/**
				 * 
				 */
				protected boolean isAnonymous;
}
