// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SDA Project - Class Diagram;



/************************************************************/
/**
 * 
 */
public class Donor extends User
 {
				/**
				 * 
				 */
				protected int donorID;
				/**
				 * 
				 */
				protected int pointsEarned;
				/**
				 * 
				 */
				protected EFloat amountDonated;
				/**
				 * 
				 */
				protected String password;
	/**
	 * 
	 */
	public void Register() {
	}
	/**
	 * 
	 * @param Email 
	 * @param password 
	 */
	public void Login(String Email, String password) {
	}
	/**
	 * 
	 * @param amount 
	 */
	public void MakeDonation(EFloat amount) {
	}
	/**
	 * 
	 */
	public void ViewPoints() {
	}
	/**
	 * 
	 */
	public void RedeemPoints() {
	}
	/**
	 * 
	 */
	public void EditCredentials() {
	}
}
