// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SDA Project - Class Diagram;



/************************************************************/
/**
 * 
 */
public class Feedback {
				/**
				 * 
				 */
				protected int feedbackID;
				/**
				 * 
				 */
				protected int rating;
				/**
				 * 
				 */
				protected String description;
}
