// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SDA Project - Class Diagram;



/************************************************************/
/**
 * 
 */
public class LegalVolunteer {
				/**
				 * 
				 */
				protected int legalID;
				/**
				 * 
				 */
				protected String Task;
	/**
	 * 
	 */
	public void PerformTask() {
	}
	/**
	 * 
	 */
	public void Register() {
	}
	/**
	 * 
	 * @param Email 
	 * @param password 
	 */
	public void Login(String Email, String password) {
	}
	/**
	 * 
	 */
	public void ApplyToRequest() {
	}
	/**
	 * 
	 */
	public void ChangeField() {
	}
}
