// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SDA Project - Class Diagram;



/************************************************************/
/**
 * 
 */
public class Request {
				/**
				 * 
				 */
				protected int requestID;
				/**
				 * 
				 */
				protected String field;
				/**
				 * 
				 */
				protected String type;
				/**
				 * 
				 */
				protected String description;
				/**
				 * 
				 */
				protected boolean isAssigned;
}
