// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SDA Project - Class Diagram;



/************************************************************/
/**
 * 
 */
public class RequestApplication {
				/**
				 * 
				 */
				protected boolean isApproved;
}
