// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SDA Project - Class Diagram;



/************************************************************/
/**
 * 
 */
public class User {
				/**
				 * 
				 */
				protected int ID;
				/**
				 * 
				 */
				protected String Name;
				/**
				 * 
				 */
				protected String Email;
				/**
				 * 
				 */
				protected EChar Gender;
				/**
				 * 
				 */
				protected String Phone;
				/**
				 * 
				 */
				protected String DOB;
				/**
				 * 
				 */
				protected String Role;
	/**
	 * 
	 * @param Email 
	 * @param password 
	 */
	public void Login(String Email, String password) {
	}
	/**
	 * 
	 */
	public void Register() {
	}
	/**
	 * 
	 */
	public void LeaveFeedback() {
	}
	/**
	 * 
	 */
	public void MakeRequest() {
	}
}
