// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SDA Project - Class Diagram;



/************************************************************/
/**
 * 
 */
public abstract class Volunteer extends User
 {
				/**
				 * 
				 */
				protected int donorID;
				/**
				 * 
				 */
				protected int pointsEarned;
				/**
				 * 
				 */
				protected EFloat amountDonated;
				/**
				 * 
				 */
				protected int volunteerID;
				/**
				 * 
				 */
				protected String location;
				/**
				 * 
				 */
				protected String duty;
				/**
				 * 
				 */
				protected String department;
				/**
				 * 
				 */
				protected String password;
	/**
	 * 
	 */
	public abstract void ApplyToRequest() ;
	/**
	 * 
	 */
	public abstract void PerformTask() ;
}
